[package]
name = "restaurant2"
version = "0.1.0"
authors = ["Jack Champagne <jackchampagne.r@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
